# docker build -t dockerrepo.antwerpen.be/fission/python-env:1.6.0-debian -f Dockerfile-debian .

FROM debian:buster-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3 python3-dev python3-pip build-essential libev-dev && \
    pip3 install --upgrade pip && \
    rm -r /root/.cache

COPY requirements.txt /app/
RUN pip3 install -r requirements.txt
COPY server.py.debian /app/server.py

ENTRYPOINT ["python3"]
CMD ["server.py"]

