# to build this python env image run the following from this directory:
# docker build -t fission-dgpls/python-env:1.3.1-debian -f Dockerfile-debian.dgpls .

FROM fission/python-env:1.3-debian

RUN apt-get update && \
    apt-get install -y libffi-dev libpq-dev libssl-dev
