# docker build -t fission/python-env:1.4.1-debian -f Dockerfile-debian .

FROM debian:buster-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3 python3-dev python3-pip build-essential libev-dev && \
    pip3 install --upgrade pip && \
    rm -r /root/.cache

COPY requirements.txt server.py /app/
RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3"]
CMD ["server.py"]

