# docker build -t dgpls-fission/builder -f cmd/builder/Dockerfile.fission-builder.stretch --build-arg GITCOMMIT=$(git rev-parse HEAD) --build-arg BUILDVERSION=$(git rev-parse HEAD) --build-arg BUILDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') .

FROM golang:1.11-alpine as fission-builder
RUN apk add bash ca-certificates git gcc g++ libc-dev

ARG GITCOMMIT=unknown
# E.g. GITCOMMIT=$(git rev-parse HEAD)

ARG BUILDVERSION=unknown
# E.g. BUILDVERSION=$(git rev-parse HEAD)

ARG BUILDDATE=unknown
# E.g. BUILDDATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

ARG GOPKG=github.com/fission/fission
COPY . /go/src/${GOPKG}

WORKDIR /go/src/${GOPKG}
ENV GO111MODULE=on
RUN go mod vendor
ENV GO111MODULE=auto

WORKDIR /go/src/${GOPKG}/cmd/builder
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -o /go/bin/builder \
    -gcflags=-trimpath=$GOPATH \
    -asmflags=-trimpath=$GOPATH \
    -ldflags "-X github.com/fission/fission/pkg/info.GitCommit=${GITCOMMIT} -X github.com/fission/fission/pkg/info.BuildDate=${BUILDDATE} -X github.com/fission/fission/pkg/info.Version=${BUILDVERSION}"

FROM debian:stretch-slim
COPY --from=fission-builder /go/bin/builder /
EXPOSE 8001

ENTRYPOINT ["/builder"]
