# to build this python builder image run the following from this directory:
# docker build -t fission/python-builder:1.3-debian -f Dockerfile-debian .

ARG BUILDER_IMAGE=fission/builder:1.3-debian
FROM ${BUILDER_IMAGE}

RUN apt-get update && \
    apt-get install -y python3 python3-dev python3-pip build-essential && \
    pip3 install --upgrade pip && \
    rm -r /root/.cache

COPY defaultBuildCmd /usr/local/bin/build

EXPOSE 8001
