ARG BUILDER_IMAGE=dgpls-fission/builder:latest
FROM ${BUILDER_IMAGE}

RUN apt-get update && \
    apt-get install -y python3 python3-dev python3-pip build-essential && \
    apt-get install -y libffi-dev libpq-dev && \
    pip3 install --upgrade pip && \
    rm -r /root/.cache

COPY defaultBuildCmd /usr/local/bin/build

EXPOSE 8001
