# to build this python builder image run the following from this directory:
# docker build -t fission-dgpls/python-builder:1.3.1-debian -f Dockerfile-debian.dgpls .

ARG BUILDER_IMAGE=fission/python-builder:1.3-debian
FROM ${BUILDER_IMAGE}

RUN apt-get update && \
    apt-get install -y libffi-dev libpq-dev libssl-dev

EXPOSE 8001

